---

# https://icinga.com/docs/icinga-certificate-monitoring/latest/doc/02-Installation/

- name: Clone the x509 Module
  git:
    repo: https://github.com/Icinga/icingaweb2-module-x509
    dest: /usr/share/icingaweb2/modules/x509

- name: run the mysql schema for the x509 database
  shell: mysql -u {{ icingaweb2_x509_db_user }} -p{{ icingaweb2_x509_db_password }} {{ icingaweb2_x509_db_name }} < /usr/share/icingaweb2/modules/x509/etc/schema/mysql.schema.sql 2> /dev/null
  args:
    executable: /bin/bash

- name: create the x509 config folder
  file:
    path: /etc/icingaweb2/modules/x509
    state: directory
    owner: www-data
    group: icingaweb2
    mode: 2770

- name: create modules/x509/config.ini
  template:
    src: modules/x509/config.ini
    dest: /etc/icingaweb2/modules/x509/config.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: enable x509 module
  shell: icingacli module enable x509
  args:
    executable: /bin/bash

...
