---

- name: create authentication.ini
  template:
    src: authentication.ini
    dest: /etc/icingaweb2/authentication.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: create config.ini
  template:
    src: config.ini
    dest: /etc/icingaweb2/config.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: create groups.ini
  template:
    src: groups.ini
    dest: /etc/icingaweb2/groups.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: create resources.ini
  template:
    src: resources.ini
    dest: /etc/icingaweb2/resources.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: create roles.ini
  template:
    src: roles.ini
    dest: /etc/icingaweb2/roles.ini
    owner: www-data
    group: icingaweb2
    mode: 0660

- name: run the mysql schema
  shell: mysql -u {{ icingaweb2_db_user }} -p{{ icingaweb2_db_password }} {{ icingaweb2_db_name }} < /usr/share/icingaweb2/etc/schema/mysql.schema.sql 2> /dev/null
  args:
    executable: /bin/bash

- name: create the password hash
  shell: php -r 'echo password_hash("{{ icingaweb2_default_password }}", PASSWORD_DEFAULT);'
  args:
    executable: /bin/bash
  register: _password_hash

- name: set the initial db user
  shell: mysql -u {{ icingaweb2_db_user }} -p{{ icingaweb2_db_password }} {{ icingaweb2_db_name }} -Ns -e 'INSERT INTO icingaweb_user (name, active, password_hash) VALUES ("{{ icingaweb2_default_user }}", 1, "{{ _password_hash.stdout }}")'
  args:
    executable: /bin/bash

- name: restart apache2
  systemd:
    name: apache2
    state: restarted

...
